# Developer environment
name: pyjanitor-examples
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyjanitor>=0.22.0
  - ipykernel
  - jupyter
  - jupyterlab
  - mkdocs
  - mkdocs-material
  - numpy
  - openpyxl
  - pandas
  - pip
  - pre-commit
  - pyprojroot
  - scipy
  - seaborn
  - pip:
      - mknotebooks
