site_name: pyjanitor documentation
site_url: https://pyjanitor-devs.github.io/pyjanitor

docs_dir: docs/

theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  icon:
    logo: "fontawesome/solid/book"
  features:
    - instant
    # - tabs
  language: en

# We customize the navigation by hand to control the order
# in which pages show up.
# nav:
#   - Home: index.md

plugins:
  - search
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         rendering:
  #           show_source: true
  #         # https://github.com/mkdocstrings/mkdocstrings/issues/278#issuecomment-831411193
  #         selection:
  #           docstring_style: restructured-text
  #     # custom_templates: templates
  #     watch:
  #       - janitor/
  - mknotebooks:
      execute: true
      write_markdown: true
      allow_errors: true
      timeout: 1200
      binder: true
      binder_service_name: "gh"
      binder_branch: "dev"

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  # - codehilite
  - admonition
  - pymdownx.highlight:
      # This option will let us use JS instead of Pygments - which worked in my hands.
      use_pygments: false
  - pymdownx.inlinehilite
  # - pymdownx.tabbed
  # - pymdownx.arithmatex
  # - pymdownx.details
  # - pymdownx.superfences
  # - markdown.extensions.attr_list

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - js/config.js

extra_css:
  - css/nb_mods.css
  - css/apidocs.css
  # This sets the theme for syntax highlighting.
  # Theme names are available here: https://highlightjs.org/static/demo/
  # Not sure how the theme names map onto CSS filenames though.
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/nord.min.css

repo_name: "pyjanitor-devs/pyjanitor"
repo_url: "https://github.com/pyjanitor-devs/pyjanitor"
